### ISSUE TITLE
More information on Architecture used

### ISSUE THREAD

**Issue by topksampler** [Puru-Malhotra/Lecture-Notes-Generator#1]
Hey! Great work! However, the architecture is tough to decipher since all the code is together. Do you have any references or any additional files that one should know of? I have been working on a similar project. LMK of any information that one should know to get this project going. I sense a few trained models are missing.

**Comment by Puru-Malhotra** [comment]
Hi! I used a hybrid Pointer generator summarization technique where I used pointing to pick up an abstract from the text and later build them into sentences. The model architecture and choice of the dataset were altered at some points after experimentation for the project due to the use of Multilingual mode of teaching in an Indian classroom, so you may experience difficulty by a break of flow at places. You can refer to this paper, a great read, to get an illustrative view of the basic architecture for the summarization part(https://arxiv.org/pdf/1704.04368.pdf)
